-- AlterEnum
ALTER TYPE "SubmissionStatus" ADD VALUE 'COMPILE_TIME_ERROR';

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "easy" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "githubUrl" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "hard" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "instagramUrl" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "linkedinUrl" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "medium" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "youtubeUrl" TEXT NOT NULL DEFAULT '';
