import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {ThemeProvider} from "next-themes";
import { Providers } from "@/redux-toolkit/Provider";
import { Cedarville_Cursive } from 'next/font/google'
<<<<<<< HEAD
import { Toaster } from "@/components/ui/sonner"
=======

>>>>>>> 08d2792acebb2929a1d39e405bed66bb0f12d4ac

const inter = Inter({ subsets: ["latin"] , variable: '--font-inter' });
const cedarville = Cedarville_Cursive({subsets: ['latin'] ,weight: '400' , style: ['normal'] , variable: '--font-cedarville'});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "Codeitup",
  description: "The Only Platform You Need To Master DSA!",
=======
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> 08d2792acebb2929a1d39e405bed66bb0f12d4ac
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
          <Providers>
            {children}
          </Providers>
<<<<<<< HEAD
          <Toaster/>
=======
>>>>>>> 08d2792acebb2929a1d39e405bed66bb0f12d4ac
        </ThemeProvider>
        </body>
    </html>
  );
}
